### ISSUE TITLE
Make a policy forbidding ruling on assassination markets

### ISSUE THREAD

**Issue by clesaege** [kleros/policies#4]
Jurors would need to vote 0  (refuse to arbitrate) if a ruling would help an assassination market to be functional.
We may need to think a bit about how phrase it, because:
-If it's too restrictive, someone could make a "life oracle" contract. The jurors would rule on the life Oracle contract and the assassination market would take data from the "life oracle" contract.
-If it's too broad, even contracts which would legitimately need to know if someone is dead would not be able too (for example a life insurance contract).

**Comment by bionexus** [comment]
The policy I have come up with goes as follows:


§ 1 Validity of Assasination Contracts
Assasination contracts are null and void. All claims resulting from them are to be rejected. [=vote 0]

§ 2 Definition
An assasination contract is any contract that
1. demands somebody to kill another person
2. demands somebody to illegaly assault another person,
3. creates markets to match those users searching for and providing assasinations or
4. creates an incentive to kill another person.
[We do not only try to define an assassination contract by it content but also by the purpose it serves. So that should do it imo. It allows the jurors to use their own reason when deciding what is an assasination contract.

**Comment by clesaege** [comment]
Would a life insurance contract be subject to 4. ?

**Comment by bionexus** [comment]
Hard to tell. It depends on the way jurors interpret it. In most European law systems the issue would be resolved by arguing the purpose of the policy is not to ban life insurance but to protect people from assassination.

We could leave that case up to the jurors' voting or we could phrase it like:

"a contract that against the moral law creates an incentive..." 

Moral law is very unprecise so here it again depends on the jurors.

I do not see it as quite a dramatic issue anyway, because legislators can never cover all possible cases so the judicative has to create principles that amend the law. And the point of Kleros is to resolve disputes with jurors that vote according to common sense and are not "prejudiced" by years of law school.
